# Generated by Django 3.2.9 on 2023-04-06 21:51

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='nome', unique=True)),
                ('nome', models.CharField(max_length=250)),
                ('descricao', models.TextField(blank=True, max_length=250, null=True)),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('imagem', stdimage.models.StdImageField(upload_to='produto_imagens/%Y/%m/')),
                ('preco_marketing', models.FloatField(validators=[django.core.validators.MinValueValidator(0.01)])),
                ('preco_marketing_promocional', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('largura', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('altura', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('comprimento', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.categoria')),
            ],
        ),
    ]
