# Generated by Django 3.2.7 on 2021-09-04 02:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('descricao_curta', models.TextField(blank=True, max_length=50, null=True)),
                ('descricao_longa', models.TextField(blank=True, max_length=250, null=True)),
                ('quantidade', models.IntegerField(default=1)),
                ('imagem', models.ImageField(blank=True, upload_to='produto_imagens/%Y/%m/')),
                ('preco_marketing', models.FloatField()),
                ('preco_marketing_promocional', models.FloatField(default=0)),
                ('tipos', models.CharField(choices=[('V', 'Variação'), ('S', 'Simples')], default='V', max_length=1)),
                ('largura', models.IntegerField(blank=True, null=True)),
                ('altura', models.IntegerField(blank=True, null=True)),
                ('comprimento', models.IntegerField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produtos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Variacao',
            fields=[
                ('cod_varicao', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=50, null=True)),
                ('preco', models.FloatField()),
                ('preco_promocional', models.FloatField(blank=True, default=0, null=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('material', models.CharField(max_length=50)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Variável',
                'verbose_name_plural': 'Variações',
            },
        ),
    ]
