# Generated by Django 3.2.7 on 2021-09-15 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cupom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('valor', models.FloatField(blank=True)),
                ('percentual', models.PositiveIntegerField(blank=True)),
                ('data_inicio', models.DateTimeField(blank=True)),
                ('data_final', models.DateTimeField(blank=True)),
                ('quantidade', models.PositiveIntegerField(blank=True, default=1)),
                ('status', models.CharField(choices=[('ATIVADO', '1'), ('DESATIVADO', '0')], default='ATIVADO', max_length=10)),
            ],
            options={
                'verbose_name': 'Cupom',
                'verbose_name_plural': 'Cupons',
            },
        ),
    ]
