# Generated by Django 3.2.7 on 2021-09-15 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='data_inicio',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='percentual',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='cupom',
            name='valor',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
