# Generated by Django 3.2.7 on 2021-09-15 02:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0002_auto_20210914_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='data_inicio',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
