# Generated by Django 3.2.7 on 2021-09-15 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cupom', '0003_alter_cupom_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cupom',
            name='data_final',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
