# Generated by Django 3.2.7 on 2021-10-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='transportadora',
        ),
        migrations.DeleteModel(
            name='Transportadora',
        ),
    ]
