# Generated by Django 3.2.7 on 2021-09-14 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='produto_id',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='variacao',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='variacao_id',
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='imagem',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto'),
        ),
    ]
